# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170413_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
